name = "BagOfWords"
uuid = "87b137f8-3b59-4550-8c54-1b47926674ff"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "0.2.2"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KNearestCenters = "4dca28ae-43b8-11eb-1f5e-d55054101997"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TextSearch = "7f6f6c8a-3b03-11e9-223d-e7d88259bd6c"

[compat]
CodecZlib = "0.7"
DataFrames = "1.6"
Downloads = "1.6"
JLD2 = "0.4"
JSON = "0.21"
KNearestCenters = "0.7"
LIBSVM = "0.8"
MLUtils = "0.2"
Random = "^1.0"
SimilaritySearch = "0.10"
StatsAPI = "1.7"
StatsBase = "0.33"
TextSearch = "0.17.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
